export const membersData = [
    {
        id: 1,
        name: "Oderinde Michael",
        gender: "Male",
        band: "Jeremiah",
        unit: "IT",
        class: "ETS",
        status: "Pending",
    },
    {
        id: 2,
        name: "Oderinde Ite",
        gender: "Female",
        band: "Rhoda",
        unit: "Secretariat",
        class: "Baptismal",
        status: "Approved",
    },
    {
        id: 3,
        name: "Oderinde Sam",
        gender: "Male",
        band: "Joseph",
        unit: "Choir",
        class: "ETS",
        status: "Approved",
    },
    {
        id: 2,
        name: "Adegoke Iseoluwa",
        gender: "Male",
        band: "Jeremiah",
        unit: "Programs",
        class: "Baptismal",
        status: "Disapproved",
    },
    {
        id: 2,
        name: "Adeife Boluwatife",
        gender: "Female",
        band: "Rhoda",
        unit: "Secretariat",
        class: "Baptismal",
        status: "Pending",
    },
]